apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      annotations:
        # invokes a redeployment if configuration changes
        {{- if .Values.config.configFile.enabled }}
        {{- $configFile := .Values.config.configFile.path }}
        config-sha: {{ sha256sum (.Files.Get $configFile) }}
        {{- end }}

      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:

      volumes:

        {{- if .Values.config.configFile.enabled }}
        - name: config
          configMap:
            name: {{ .Chart.Name }}-config
        {{- end }}

        - name: homebridge-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvclaim

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            - name: homebridge-data
              mountPath: /homebridge

            {{- if .Values.config.configFile.enabled }}
            - name: config
              mountPath: /homebridge/config.json
              subPath: config.json
            {{- end }}

          securityContext:
            privileged: true

          env:
            - name: TZ
              value: "{{ .Values.environment.timezone }}"
            - name: ENABLE_AVAHI
              value: "{{ .Values.environment.enableAvahi }}"

          ports:
            - name: {{ .Values.ports.ui.name }}
              containerPort: {{ .Values.ports.ui.number }}
              protocol: {{ .Values.ports.ui.protocol }}

            - name: {{ .Values.ports.service.name }}
              containerPort: {{ .Values.ports.service.number }}
              protocol: {{ .Values.ports.service.protocol }}

          readinessProbe:
            tcpSocket:
              port: {{ .Values.ports.ui.name }}
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: {{ .Values.ports.ui.name }}
            initialDelaySeconds: 120
            periodSeconds: 30

      hostNetwork: true

      {{- if .Values.affinity.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.affinity.weight }}
              preference:
                matchExpressions:
                  - key: "{{ .Values.affinity.label }}"
                    operator: In
                    values:
                      {{- range .Values.affinity.value }}
                      - {{ . | quote }}
                      {{- end }}
      {{- end }}
