apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  selector:
    app: {{ .Chart.Name }}
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
  {{- with .Values.service.ip }}
  loadBalancerIP: {{ . }}
  {{- end }}

  ports:
  - name: {{ .Values.ports.ui.name }}
    port: {{ .Values.ports.ui.number }}
    protocol: {{ .Values.ports.ui.protocol }}
    targetPort: {{ .Values.ports.ui.name }}
  - name: {{ .Values.ports.service.name }}
    port: {{ .Values.ports.service.number }}
    protocol: {{ .Values.ports.service.protocol }}
    targetPort: {{ .Values.ports.service.name }}