apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homebridge-cluster
image: rancher/k3s:v1.32.1-k3s1
servers: 1
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
# registries: # define how registries should be created or used
#   # create: true # creates a default registry to be used with the cluster; same as `--registry-create`
